apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    name: backend
    app: backend
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
    "prometheus.io/probe": "true"
    "prometheus.io/scrape": "true"
    "prometheus.io/port": "8080"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: nesspll/backend:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    release: prometheus
    app: backend
  annotations:
    "prometheus.io/probe": "true"
    "prometheus.io/scrape": "true"
    "prometheus.io/port": "8080"
spec:
  selector:
    app: backend
  ports:
    - name: metrics
      port: 8081
      targetPort: 5000
  type: LoadBalancer