apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    name: frontend
    app: frontend
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
    "prometheus.io/probe": "true"
    "prometheus.io/scrape": "true"
    "prometheus.io/port": "8080"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: nesspll/frontend:v2
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    release: prometheus
    app: frontend
  annotations:
    "prometheus.io/probe": "true"
    "prometheus.io/scrape": "true"
    "prometheus.io/port": "8080"
spec:
  selector:
    app: frontend
  ports:
    - name: metrics
      port: 8080
      targetPort: 5000
  type: LoadBalancer