{
 "title": "Flask App",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "Jaeger Flask Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Backend Total Latency",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "query": "0d4307c", "service": "service-backend" }
   ]
  },
  {
   "title": "Frontend Total Latency",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "query": "0d4307c", "service": "service-frontend" }
   ]
  },
  { "title": "Flask Application Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Backend Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - process_start_time_seconds{service=\"backend-service\"})"
    }
   ]
  },
  {
   "title": "Frontend Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - process_start_time_seconds{service=\"frontend-service\"})"
    }
   ]
  },
  {
   "title": "Requests per second - Backend",
   "type": "graph",
   "description": "Requests per second ",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(app_request_count_total{service=~\"backend-service\", exported_endpoint=~\"/\", method=~\"GET\"}[1m])"
    }
   ]
  },
  {
   "title": "Requests per second - Frontend",
   "type": "graph",
   "description": "Requests per second ",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(app_request_count_total{service=~\"frontend-service\", exported_endpoint=~\"/\", method=~\"GET\"}[1m])"
    }
   ]
  },
  {
   "title": "Request Latency, Backend",
   "type": "graph",
   "description": "Latency per pod, endpoint and method",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(app_request_latency_seconds_sum{service=\"backend-service\", exported_endpoint=~\"/\", method=~\"GET\"}[1m]) \n/ \nrate(app_request_latency_seconds_count{service=\"backend-service\", exported_endpoint=~\"/\", method=~\"GET\"}[1m])"
    }
   ]
  },
  {
   "title": "Request Latency, Frontend",
   "type": "graph",
   "description": "Latency per pod, endpoint and method",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(app_request_latency_seconds_sum{service=\"frontend-service\", exported_endpoint=~\"/\", method=~\"GET\"}[1m]) \n/ \nrate(app_request_latency_seconds_count{service=\"frontend-service\", exported_endpoint=~\"/\", method=~\"GET\"}[1m])"
    }
   ]
  },
  {
   "title": "CPU usage Backend",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{service=~\"backend-service\"}[1m])",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Memory usage Backend",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{service=\"backend-service\"}"
    }
   ]
  },
  {
   "title": "CPU usage Frontend",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{service=~\"frontend-service\"}[1m])",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Memory usage Frontend",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{service=\"frontend-service\"}"
    }
   ]
  },
  {
   "title": "4xx, 5xx errors per second - Backend",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(app_request_count_total{http_status=~\"4..|5..\", service=~\"backend-service\"}[1m]))",
     "legendFormat": " Errors per second"
    }
   ]
  },
  {
   "title": "4xx, 5xx errors per second - Frontend",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(app_request_count_total{http_status=~\"4..|5..\", service=~\"frontend-service\"}[1m]))",
     "legendFormat": " Errors per second"
    }
   ]
  },
  {
   "title": "Backend 200 Http Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(app_request_count_total{http_status=~\"200\", service=~\"backend-service\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Frontend 200 Http Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(app_request_count_total{http_status=~\"200\", service=~\"frontend-service\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Latency within which 100% of requests served",
   "type": "timeseries",
   "description": "See more:\nhttps://prometheus.io/docs/practices/histograms/",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(100 / 100, sum(rate(app_request_latency_seconds_bucket[1m])) by (le))",
     "legendFormat": "latency"
    }
   ]
  },
  { "title": "BlackBox Exporter for Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Global Probe Of Services",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{instance=~\"backend-service.default.svc:8081|frontend-service.default.svc:8080\"}"
    }
   ]
  },
  {
   "title": "Backend Service",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=~\"backend-service.default.svc:8081\"}"
    }
   ]
  },
  {
   "title": "HTTP Duration - Backend Service",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 4, "y": 58 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_http_duration_seconds{instance=~\"backend-service.default.svc:8081\"}"
    }
   ]
  },
  {
   "title": "Frontend Probe Duration",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{instance=~\"backend-service.default.svc:8081\"}",
     "legendFormat": "seconds"
    }
   ]
  },
  {
   "title": "B - Average Probe Duration",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{instance=~\"backend-service.default.svc:8081\"})"
    }
   ]
  },
  {
   "title": "HTTP Status Code ",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_status_code{instance=~\"backend-service.default.svc:8081\"}"
    }
   ]
  },
  {
   "title": "B - Average DNS Lookup",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{instance=~\"backend-service.default.svc:8081\"})"
    }
   ]
  },
  {
   "title": "Frontend Service",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=~\"frontend-service.default.svc:8080\"}"
    }
   ]
  },
  {
   "title": "HTTP Duration - FrontEnd Service",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 4, "y": 62 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_http_duration_seconds{instance=~\"frontend-service.default.svc:8080\"}"
    }
   ]
  },
  {
   "title": "Frontend Probe Duration",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{instance=~\"frontend-service.default.svc:8080\"}",
     "legendFormat": "seconds"
    }
   ]
  },
  {
   "title": "F - Average Probe Duration",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{instance=~\"backend-service.default.svc:8081\"})"
    }
   ]
  },
  {
   "title": "HTTP Status Code ",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_status_code{instance=~\"frontend-service.default.svc:8080\"}"
    }
   ]
  },
  {
   "title": "F - Average DNS Lookup",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{instance=~\"backend-service.default.svc:8081\"})"
    }
   ]
  }
 ]
}